import { chromium } from '/home/claude/.npm-global/lib/node_modules/playwright/index.mjs';
const OUT = process.argv[2];
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const ctx = await browser.newContext({ viewport: { width: 393, height: 852 }, deviceScaleFactor: 2 });
await ctx.route('**/rest/v1/rpc/**', (route) => {
  const fn = route.request().url().split('/rpc/')[1];
  const body = JSON.parse(route.request().postData() || '{}');
  if (fn === 'oche_reset_player') {
    if (body.p_code !== 'x') return route.fulfill({ status: 400, contentType: 'application/json', body: JSON.stringify({ message: 'bad_code' }) });
    return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(new Date().toISOString()) });
  }
  const d = fn === 'oche_join' ? { id: 'team-x', name: 'Test', has_admin: false } : fn === 'oche_check' ? true : fn === 'oche_players' ? [{ id: 'p1', name: 'Yves', color: '#5fc8ff' }] : fn === 'oche_games' ? [] : null;
  return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(d) });
});
const page = await ctx.newPage();
const errs = []; page.on('pageerror', (e) => errs.push(String(e)));
await page.goto('http://localhost:4173');
await page.getByText('Rejoindre une équipe').click();
await page.getByLabel("Code de l'équipe").fill('x');
await page.getByRole('button', { name: 'Continuer' }).click();
await page.getByRole('button', { name: 'Rejoindre' }).click();
await page.getByRole('button', { name: /Yves/ }).first().click();
await page.getByRole('button', { name: 'Réglages' }).click();
await page.getByRole('switch', { name: 'Mode démo' }).click();
await page.getByRole('button', { name: 'OK' }).click();
await page.getByRole('button', { name: 'Stats' }).click();
const t0 = Date.now();
await page.getByText('simulés sur 6 mois').waitFor({ timeout: 30000 });
console.log('demo ready in', Date.now() - t0, 'ms');
await page.getByRole('button', { name: /^Yves/ }).click();
await page.screenshot({ path: `${OUT}/dbg.png` }); await page.locator('[role=option]', { hasText: 'Testeur' }).click();
await page.screenshot({ path: `${OUT}/a0-resume.png`, fullPage: true });
await page.getByRole('radio', { name: 'Analyse' }).click();
await page.waitForTimeout(400);
await page.getByRole('button', { name: /Voir les \d+ stats/ }).click();
await page.waitForTimeout(200);
await page.screenshot({ path: `${OUT}/a1-x01.png`, fullPage: true });
await page.locator('.chip-pill', { hasText: '3 mois' }).click();
await page.waitForTimeout(300);
if (!(await page.locator('.ftable').count())) await page.getByRole('button', { name: /Voir les \d+ stats/ }).click();
await page.locator('.ftable').screenshot({ path: `${OUT}/a1b-tendances.png` });
console.log('tendances: up', await page.locator('.ftable .tr-up').count(), 'down', await page.locator('.ftable .tr-down').count());
for (const m of ['Cricket', 'Shanghai', 'ATC']) {
  await page.locator('.mode-tabs button', { hasText: m }).click();
  await page.waitForTimeout(300);
  await page.screenshot({ path: `${OUT}/a-${m}.png`, fullPage: true });
}
await page.getByRole('radio', { name: 'Succès' }).click();
await page.waitForTimeout(300);
await page.screenshot({ path: `${OUT}/a9-succes.png`, fullPage: true });
await page.locator('.mode-tabs button', { hasText: 'Paliers' }).click();
await page.waitForTimeout(200);
await page.locator('.ach button', { hasText: 'Triples' }).first().click();
await page.waitForTimeout(200);
await page.screenshot({ path: `${OUT}/a9b-paliers.png`, fullPage: true });
await page.getByRole('button', { name: 'Classement' }).click();
await page.waitForTimeout(300);
await page.screenshot({ path: `${OUT}/a10-classement.png` });
// remise à zéro (sur le Testeur de démo, via la vraie liste de joueurs : Yves)
await page.getByRole('button', { name: 'Jouer' }).click();
await page.getByRole('button', { name: 'Réglages' }).click();
await page.getByRole('button', { name: 'Zone sensible' }).click();
await page.getByLabel('Joueur à remettre à zéro').selectOption({ label: 'Yves' });
await page.getByLabel("Code de l'équipe pour confirmer").fill('faux');
await page.getByRole('button', { name: 'Remettre Yves à zéro' }).click();
await page.getByText('Code incorrect.').waitFor();
await page.screenshot({ path: `${OUT}/r1-reset-erreur.png` });
await page.getByLabel('Joueur à remettre à zéro').selectOption({ label: 'Yves' });
await page.getByLabel("Code de l'équipe pour confirmer").fill('x');
await page.getByRole('button', { name: 'Remettre Yves à zéro' }).click();
await page.getByText('repart de zéro').waitFor();
await page.screenshot({ path: `${OUT}/r2-reset-ok.png` });
console.log('reset OK');
console.log('errors:', errs.length ? errs : 'none');
await browser.close();
